
/**
* CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Freitag, 3. Juli 2015 10:57 Uhr MESZ
*/

public interface CalcOperations 
{
  int add (int x, int y);
  int subtr (int x, int y);
  int mult (int x, int y);
  int div (int x, int y) throws DivByZero;
} // interface CalcOperations
