
/**
* CalcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Freitag, 3. Juli 2015 10:31 Uhr MESZ
*/

public final class CalcHolder implements org.omg.CORBA.portable.Streamable
{
  public Calc value = null;

  public CalcHolder ()
  {
  }

  public CalcHolder (Calc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalcHelper.type ();
  }

}
