
/**
* DivByZeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Freitag, 3. Juli 2015 10:58 Uhr MESZ
*/

public final class DivByZeroHolder implements org.omg.CORBA.portable.Streamable
{
  public DivByZero value = null;

  public DivByZeroHolder ()
  {
  }

  public DivByZeroHolder (DivByZero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DivByZeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DivByZeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DivByZeroHelper.type ();
  }

}
